### ISSUE TITLE
repo is missing  index

### ISSUE THREAD

**Issue by mrafea-sa** [JimmyTheJ/web-server#1]
@JimmyTheJ
This repo is missing  index.html , to load js.
even after adding the file nothing work!
Also windows does not support folder names that include dot i.e. ".well-known"

**Comment by JimmyTheJ** [comment]
I'll look into moving this to using a static index.html with webpack HTML plugin to get that working and as for windows not supporting dot folders, it does... it's just a little finnicky about letting you create them. I'll put an option in appsettings.json to disable exposing .well-known folder so that error doesn't come up if you don't have it.
